# Generated by Django 4.2.13 on 2024-06-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='josaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institute', models.CharField(max_length=250, verbose_name='Institute')),
                ('Academic_Program_Name', models.CharField(max_length=300, verbose_name='Academic_Program_Name')),
                ('Seat_Type', models.CharField(max_length=50, verbose_name='Seat_Type')),
                ('Gender', models.CharField(max_length=50, verbose_name='Gender')),
                ('Opening_Rank', models.IntegerField(default=0, verbose_name='Opening_Rank')),
                ('Closing_Rank', models.IntegerField(default=0, verbose_name='Closing_Rank')),
                ('year', models.IntegerField(verbose_name='year')),
                ('round', models.IntegerField(verbose_name='round')),
            ],
        ),
    ]
